### ISSUE TITLE
armacmp vs. ast2ast

### ISSUE THREAD

**Issue by coatless** [Konrad1991/ast2ast#1]
@Konrad1991 before going further, check out @dirkschumacher's work:

https://github.com/dirkschumacher/armacmp
https://github.com/dirkschumacher/armacmp-shiny

**Comment by Konrad1991** [comment]
@dirkschumacher I have developed in the last few weeks an expression template library (https://github.com/Konrad1991/ETR) which behaves almost the same as R itself. So my aim for ast2ast is to  write R code which translates R to ETR. 
However, I need a bit of support because I don't get my R code well structured.  Would you be interested in participating?

**Comment by dirkschumacher** [comment]
@Konrad1991 I don't have the capacity at the moment to help with another project, but I can tell you how I did it with {armacmp}.

{armacmp} also has some kind of intermediate representation. I take an R ast (an R expression (unevaluated R code)) and ["annotate" it](https://github.com/dirkschumacher/armacmp/blob/master/R/annotate-ast.R). After that I get a representation of the original R AST in form of my custom ["AST classes"](https://github.com/dirkschumacher/armacmp/blob/master/R/ast-classes.R). These AST classes can self translate to C++ and support things like scopes, lambdas, etc.

So you could do the same, take an R expression -> translate it to your own intermediate representation in R -> translate to ETR c++ -> compile to machine code.

**Comment by Konrad1991** [comment]
@dirkschumacher thank you very much for your help. This will help me structuring my code. I tried to directly translate the R ast into the C++ code which results in completely unstructured code ;)
