### ISSUE TITLE
Performance of Leibniz formula

### ISSUE THREAD

**Issue by kadyb** [Konrad1991/ast2ast#3]
Fantastic idea for package! Recently there was an interesting benchmark comparing different programming languages for calculating pi using Leibniz formula (https://github.com/niklas-heer/speed-comparison). I was curious what the benefits would be of using `{ast2ast}` and here are the results:

```r
leibniz = function(rounds) {
  x = 1.0
  pi = 1.0
  for (i in 2:(rounds + 2)) {
    x = x * -1
    pi = pi + (x / (2 * i - 1))
  }
  pi = pi * 4
  return(pi)
}

leibniz_vectorized = function(rounds) {
  pi = sum(4 / seq.int(-2 * rounds + 1, 2 * rounds, by = 4))
  return(pi)
}

leibniz_cpp = ast2ast::translate(leibniz)

rounds = 10000000
system.time(leibniz(rounds)) #> 1.171
system.time(leibniz_vectorized(rounds)) #> 0.235
system.time(leibniz_cpp(rounds)) #> 2.323
```

So it looks like the computation is slower than in R. I also tried to translate the `leibniz_vectorized()`, but `sum()` and `seq.int()` are not implemented.

**Comment by Konrad1991** [comment]
I have no time to explain it in detail this weekend. On Monday I have time and will explain it in detail. Sorry for that.

**Comment by kadyb** [comment]
No problem!

**Comment by Konrad1991** [comment]
So the explanation is that the R interface is only for testing. At least currently the performance is not optimal. There are some tricks however to improve the performance. In the code below there is a solution that is even faster than the vectorized version. However, only ca. factor of 2 times faster. This is due to the fact that not too much code is running. 
```R
leibniz = function(rounds) {
  x = 1.0
  pi = 1.0
  for (i in 2:(rounds + 2)) {
    x = x * -1
    pi = pi + (x / (2 * i - 1))
  }
  pi = pi * 4
  return(pi)
}

leibniz2 = function(rounds) {
  x_db = 1.0
  pi_db = 1.0
  for (i in 2:(rounds + 2)) {
    x_db = x_db * -1
    pi_db = pi_db + (x_db / (2.0 * i - 1.0))
  }
  pi_db = pi_db * 4.0
  pi = pi_db
  return(pi)
}


leibniz_vectorized = function(rounds) {
  pi = sum(4 / seq.int(-2 * rounds + 1, 2 * rounds, by = 4))
  return(pi)
}

leibniz_cpp = ast2ast::translate(leibniz)
leibniz_cpp2 = ast2ast::translate(leibniz2)

rounds = 10000000
system.time(leibniz(rounds)) #> 0.538
system.time(leibniz_vectorized(rounds)) #> 0.116
system.time(leibniz_cpp(rounds)) #> 1.271
system.time(leibniz_cpp2(rounds)) #> 0.057
```

For instance, if you check the 'Run sum' example for the function 'translate' you can see that ast2ast is running faster. Still, the pure C++ version is much faster. 

Moreover, ast2ast is very useful when an external pointer is needed. Here the created C++ functions are really fast. For example, I used ast2ast to create ode systems which are afterward used for the optimization of parameters using [paropt](https://github.com/Konrad1991/paropt). Notably, the optimization evaluates parameter sets in parallel. This wouldn't be possible with pure R functions. 

Are there any questions left?

**Comment by kadyb** [comment]
Thank you very much for clarifying and improving the code! I can confirm too that on my PC `leibniz_cpp2()` function is ~2 times faster than `leibniz_vectorized()`. Great work!
